version: '3.8'

services:
  nginxProx:
    image: nginx
    hostname: domain-name-nginx
    restart: 'no'
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
        #links:
        # - docServer
        # - dopServer
    networks:
      default:
        ipv4_address: 172.20.1.1

  docServer:
    image: server-image
    hostname: domain-name-market
    restart: 'no'
    networks:
      default:
        ipv4_address: 172.20.1.2

  dopServer:
    image: httpd
    hostname: domain-name-page
    restart: 'no'
    networks:
      default:
        ipv4_address: 172.20.1.3

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/14
